spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    
  data:
    redis:
      host: redis
      port: 6379
      password: ${REDIS_PASSWORD}
      
  kafka:
    bootstrap-servers: kafka:29092
    
  liquibase:
    enabled: false
    
  jpa:
    hibernate:
      ddl-auto: create-drop
      
app:
  cors:
    allowed-origins: http://localhost:3000,https://localhost
    
  oauth2:
    redirectUri: http://localhost:3000/auth/callback